@startuml
left to right direction
actor "User" as U
actor "Admin" as A

rectangle TIMP_Project {
  usecase "Register" as UC1
  usecase "Login" as UC2
  usecase "Encrypt (Vigenere)" as UC3
  usecase "Hash (SHA-512)" as UC4
  usecase "Calculate (Bisection)" as UC5
  usecase "Find Path (Graph)" as UC6
  usecase "Change Role" as UC7
}

U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U --> UC6

A --> UC1
A --> UC2
A --> UC3
A --> UC4
A --> UC5
A --> UC6
A --> UC7
@enduml
